### ISSUE TITLE
Cannot start lsp-tsserver [WinError 2]

### ISSUE THREAD

**Issue by drewLough** [tomv564/lsp-tsserver#10]
![can't find lsp=tsserver](https://i.imgur.com/rgf45p9.png)

Probably missing something obvious, that's why it it isn't mentioned anywhere. 
Win10. 
`lsp-tsserver` is installed globally. can't determine why it's not being found. all the files that it says it can't access exist.

trace:
```
reloading settings Packages/User/LSP.sublime-settings
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 369, in <lambda>
    lambda: check_view_event_listeners(view))
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 356, in check_view_event_listeners
    want = is_view_event_listener_applicable(cls, view)
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 321, in is_view_event_listener_applicable
    if not cls.is_applicable(view.settings()):
  File "C:\Users\Drew\AppData\Roaming\Sublime Text 3\Installed Packages\LSP.sublime-package\plugin/completion.py", line 142, in is_applicable
  File "C:\Users\Drew\AppData\Roaming\Sublime Text 3\Installed Packages\LSP.sublime-package\plugin/core/configurations.py", line 89, in is_supported_syntax
  File "./python3.3/re.py", line 161, in search
TypeError: expected string or buffer
Unable to open /C/Users/Drew/AppData/Roaming/Sublime Text 3/Packages/LSP/LSP.sublime-settings
```
seem to remember resolving this issue before with `npm i -g lsp-tsserver` but that hasn't had success.

**Comment by drewLough** [comment]
absolutely no clue what happened, but something clicked and lsp-tsserver works now.
things I tried:
- reinstall sublime text
- reinstall node
- delete %Appdata%
- install python 3 (via visual studio installer)
- turned it off and on again

still encountering same (apparently unrelated) previous errors this in the console, however.

closing for now since things seem to be working.
