### ISSUE TITLE
ST3 LSP on macOS not works

### ISSUE THREAD

**Issue by dalisoft** [tomv564/lsp-tsserver#16]
Here some logs

```bash
lsp-tsserver for /Users/dalisoft/Desktop/MyScreen/myscreen-dev-env/backend did not initialize properly. Disabling until this window is restarted
Traceback (most recent call last):
  File "/Users/dalisoft/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/windows.py", line 334, in get_session
    return self._find_session(config_name, file_path)
  File "/Users/dalisoft/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/windows.py", line 344, in _find_session
    if session.handles_path(file_path):
  File "/Users/dalisoft/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/sessions.py", line 200, in handles_path
    with self.acquire_timeout():
  File "./python3.3/contextlib.py", line 48, in __enter__
  File "/Users/dalisoft/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/sessions.py", line 193, in acquire_timeout
    raise InitializeError(self)
LSP.plugin.core.sessions.InitializeError: lsp-tsserver did not respond to the initialize request within 3 seconds

```

LSP Log

```bash
lsp-tsserver: /usr/local/lib/node_modules/lsp-tsserver/node_modules/vscode-languageserver/lib/main.js:700
lsp-tsserver: throw new Error("Connection input stream is not set. " + commandLineMessage);
:: --> lsp-tsserver initialize(1): {'rootPath': '/Users/dalisoft/Desktop/MyScreen/myscreen-dev-env/backend', 'capabilities': {'workspace': {'workspaceFolders': True, 'didChangeConfiguration': {}, 'symbol': {'symbolKind': {'valueSet': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]}}, 'applyEdit': True, 'configuration': True, 'executeCommand': {}}, 'textDocument': {'completion': {'completionItem': {'snippetSupport': True}, 'completionItemKind': {'valueSet': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]}}, 'declaration': {'linkSupport': True}, 'colorProvider': {}, 'rangeFormatting': {}, 'synchronization': {'didSave': True, 'willSaveWaitUntil': True, 'willSave': True}, 'references': {}, 'publishDiagnostics': {'relatedInformation': True}, 'formatting': {}, 'documentSymbol': {'symbolKind': {'valueSet': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]}}, 'rename': {}, 'hover': {'contentFormat': ['markdown', 'plaintext']}, 'definition': {'linkSupport': True}, 'implementation': {'linkSupport': True}, 'codeAction': {'codeActionLiteralSupport': {'codeActionKind': {'valueSet': []}}}, 'signatureHelp': {'signatureInformation': {'parameterInformation': {'labelOffsetSupport': True}, 'documentationFormat': ['markdown', 'plaintext']}}, 'typeDefinition': {'linkSupport': True}, 'documentHighlight': {}}}, 'rootUri': 'file:///Users/dalisoft/Desktop/MyScreen/myscreen-dev-env/backend', 'processId': 1796, 'workspaceFolders': [{'uri': 'file:///Users/dalisoft/Desktop/MyScreen/myscreen-dev-env/backend', 'name': 'backend'}]}
:: --> lsp-tsserver shutdown(2): None
```

**Comment by dalisoft** [comment]
[This](https://github.com/emacs-lsp/lsp-mode/issues/953#issuecomment-515126071) solution worked. If anyone occurs to this bug, append `--stdio` at end and enjoy!
